import React , {  useState  }  from 'react';
import classes from "./terms.module.css";



const Privacy = () => {

  return (
    <>
      <div className='termsPage'>
          <div className="container">
            <div className="row ">
               <h3 className="pageHeading">Terms and conditions</h3>
               <p>Welcome to the Art Gallery E-commerce website , read the terms and Conditions before using the website.</p>

                <h5 className={classes.termsheading}>Terms</h5>
                <p>These terms and conditions ("Agreement") set forth the general terms and conditions of your use of the sastodeal.com website ("Website"), "Sastodeal" mobile application ("Mobile Application") and any of the related products and services (collectively, "Services"). This Agreement is legally binding between you ("User, you, your") and Sastodeal Private Limited (, "Sastodeal, we, us"). By accessing and using the Services, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement and You accept and agree to these terms and conditions and the revisions henceforth. You also accept and agree to be bound by Sastodeal Policies set out in the website and as amended from time to time. If you choose not to agree with any of these terms, you may stop using the Services immediately. Subject to You complying with these Terms of Use, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website. If you are entering into this Agreement on behalf of a business or other legal entity, you represent that you have the authority to bind such entity to this Agreement, in which case the terms "User" and “you/your” shall refer to such entity. You acknowledge that this Agreement is a contract between you and the Sastodeal, even though it is electronic and is not physically signed by you, and it governs your use of the Services, creating a binding obligation for you.</p>

                <h5 className={classes.termsheadingTwo}>Access</h5>
                <p>These terms and conditions ("Agreement") set forth the general terms and conditions of your use of the sastodeal.com website ("Website"), "Sastodeal" mobile application ("Mobile Application") and any of the related products and services (collectively, "Services"). This Agreement is legally binding between you ("User, you, your") and Sastodeal Private Limited (, "Sastodeal, we, us"). By accessing and using the Services, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement and You accept and agree to these terms and conditions and the revisions henceforth. You also accept and agree to be bound by Sastodeal Policies set out in the website and as amended from time to time. If you choose not to agree with any of these terms, you may stop using the Services immediately. Subject to You complying with these Terms of Use, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website. If you are entering into this Agreement on behalf of a business or other legal entity, you represent that you have the authority to bind such entity to this Agreement, in which case the terms "User" and “you/your” shall refer to such entity. You acknowledge that this Agreement is a contract between you and the Sastodeal, even though it is electronic and is not physically signed by you, and it governs your use of the Services, creating a binding obligation for you.</p>

                <h5 className={classes.termsheadingTwo}>Submission</h5>
                <p>These terms and conditions ("Agreement") set forth the general terms and conditions of your use of the sastodeal.com website ("Website"), "Sastodeal" mobile application ("Mobile Application") and any of the related products and services (collectively, "Services"). This Agreement is legally binding between you ("User, you, your") and Sastodeal Private Limited (, "Sastodeal, we, us"). By accessing and using the Services, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement and You accept and agree to these terms and conditions and the revisions henceforth. You also accept and agree to be bound by Sastodeal Policies set out in the website and as amended from time to time. If you choose not to agree with any of these terms, you may stop using the Services immediately. Subject to You complying with these Terms of Use, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website. If you are entering into this Agreement on behalf of a business or other legal entity, you represent that you have the authority to bind such entity to this Agreement, in which case the terms "User" and “you/your” shall refer to such entity. You acknowledge that this Agreement is a contract between you and the Sastodeal, even though it is electronic and is not physically signed by you, and it governs your use of the Services, creating a binding obligation for you.</p>


                <h5 className={classes.termsheadingTwo}>Platform</h5>
                <p>These terms and conditions ("Agreement") set forth the general terms and conditions of your use of the sastodeal.com website ("Website"), "Sastodeal" mobile application ("Mobile Application") and any of the related products and services (collectively, "Services"). This Agreement is legally binding between you ("User, you, your") and Sastodeal Private Limited (, "Sastodeal, we, us"). By accessing and using the Services, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement and You accept and agree to these terms and conditions and the revisions henceforth. You also accept and agree to be bound by Sastodeal Policies set out in the website and as amended from time to time. If you choose not to agree with any of these terms, you may stop using the Services immediately. Subject to You complying with these Terms of Use, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website. If you are entering into this Agreement on behalf of a business or other legal entity, you represent that you have the authority to bind such entity to this Agreement, in which case the terms "User" and “you/your” shall refer to such entity. You acknowledge that this Agreement is a contract between you and the Sastodeal, even though it is electronic and is not physically signed by you, and it governs your use of the Services, creating a binding obligation for you.</p>

                <h5 className={classes.termsheadingTwo}>Platform</h5>
                <p>These terms and conditions ("Agreement") set forth the general terms and conditions of your use of the sastodeal.com website ("Website"), "Sastodeal" mobile application ("Mobile Application") and any of the related products and services (collectively, "Services"). This Agreement is legally binding between you ("User, you, your") and Sastodeal Private Limited (, "Sastodeal, we, us"). By accessing and using the Services, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement and You accept and agree to these terms and conditions and the revisions henceforth. You also accept and agree to be bound by Sastodeal Policies set out in the website and as amended from time to time. If you choose not to agree with any of these terms, you may stop using the Services immediately. Subject to You complying with these Terms of Use, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website. If you are entering into this Agreement on behalf of a business or other legal entity, you represent that you have the authority to bind such entity to this Agreement, in which case the terms "User" and “you/your” shall refer to such entity. You acknowledge that this Agreement is a contract between you and the Sastodeal, even though it is electronic and is not physically signed by you, and it governs your use of the Services, creating a binding obligation for you.</p>

            </div>
          </div>
      </div>
    </>
  );
};

export default Privacy;
