export const CART = "CART";
export const SEARCH = "SEARCH";
export const CATEGORY = "CATEGORY";
export const HELP_CENTER = "HELP_CENTER";

export const SHOW_FRAME_MODAL = "SHOW_FRAME_MODAL";
export const HIDE_FRAME_MODAL = "HIDE_FRAME_MODAL";

export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
export const GET_CART = "GET_CART";

export const SUCCESS = "SUCCESS";
export const WARNING = "WARNING";
export const ERROR = "ERROR";

export const HIDE_MESSAGE = "HIDE__MESSAGE";
export const SHOW_MESSAGE = "SHOW__MESSAGE";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const USER_REGISTER = "USER_REGISTER";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const LOGIN_MODAL = "LOGIN_MODAL";

export const FETCH_EDIT_PROFILE = "FETCH_EDIT_PROFILE";
export const UPDATE__PROFILE = "UPDATE_PROFILE";
export const FORGOT__MODEL = "FORGOT__MODEL";
export const SEND_FORGOT_EMAIL = "SEND_FORGOT_EMAIL";

export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const PRODUCT_BY_CATEGORIES = "PRODUCT_BY_CATEGORIES";

export const FILTER_DATA_PRICE = "FILTER_DATA_PRICE";
export const PRODUCT = "PRODUCT";

export const SORT_BY_NAME_ASCENDING = "SORT_BY_NAME_ASCENDING";
export const SORT_BY_NAME_DESCENDING = "SORT_BY_NAME_DESCENDING";
export const SORT_BY_PRICE_ASCENDING = "SORT_BY_PRICE_ASCENDING";
export const SORT_BY_PRICE_DESCENDING = "SORT_BY_PRICE_DESCENDING";

export const FILTER_CATEGORY_BY_PRICE = "FILTER_CATEGORY_BY_PRICE";
export const FILTER_PRODUCTS_BY_PRICE = "FILTER_PRODUCTS_BY_PRICE";

export const FETCH_WISHLIST = "FETCH_WISHLIST";
export const ADD_WISHLIST_ITEM = "ADD_WISHLIST_ITEM";
export const DELETE_WISHLIST_ITEM = "DELETE_WISHLIST_ITEM";

export const TOOGLE_LIKE_ON_PRODUCT = "TOOGLE_LIKE_ON_PRODUCT";

export const TRENDING_AUCTION_FETCH = "TRENDING_AUCTION_FETCH";

export const ADD_BALANCE = "ADD_BALANCE";
export const DEDUCT_BALANCE = "DEDUCT_BALANCE";

export const SHOW_CONFIRMATION = "SHOW_CONFIRMATION";
export const HIDE_CONFIRMATION = "HIDE_CONFIRMATION";

export const FETCH_ORDER = "FETCH_ORDER";
export const REMOVE_ORDER = "REMOVE_ORDER";
export const REMOVE_ORDER_PRODUCT = "REMOVE_ORDER_PRODUCT";
